# Site settings
title: "Invocador de Nomes do Capeta"
email: josenaldo@gmail.com
description: "A lista de nomes do Capeta mais completa da internet"
baseurl: "/invocador-de-nomes-do-capeta"
url: "http://josenaldo.github.io/invocador-de-nomes-do-capeta/"
title_description: "Clique para invocar um novo nome do Tinhoso!"
title_image: "/invocador-de-nomes-do-capeta/assets/images/user.png"
google_analytics: 
disqus_account: 
github_repository: https://github.com/josenaldo/invocador-de-nomes-do-capeta
post_limit: 5

# Social usernames/URLs
twitter_username: vudureverso
github_username:  josenaldo
instagram_username: vudureverso
reddit_username: vudureverso
linkedin_link: https://www.linkedin.com/in/josenaldo/
facebook_link: https://www.facebook.com/josenaldo.matos

# Footer
footer_left: 
footer_right: 

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
