# Site settings
title: "Nomes do Capeta"
email: josenaldo@gmail.com
description: "A lista de nomes do Capeta mais completa da internet"
baseurl: "/nomesdocapeta"
url: "http://josenaldo.github.io/nomesdocapeta/"
title_description: "Clique para conhecer um dos nomes do Tinhoso!"
title_image: "/nomesdocapeta/assets/images/user.png"
google_analytics: 
disqus_account: 
github_repository: https://github.com/josenaldo/nomesdocapeta
post_limit: 5

# Social usernames/URLs
twitter_username: vudureverso
github_username:  josenaldo
instagram_username: vudureverso
reddit_username: vudureverso
linkedin_link: http://josenaldo.github.io/nomesdocapeta/
google_plus_link: http://josenaldo.github.io/nomesdocapeta/
stackoverflow_link: http://josenaldo.github.io/nomesdocapeta/
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
